full_name = input("Ваші прізвище, ім'я, по батькові?\n")
age = input("Скільки Вам років?\n")
location = input("Де Ви живете?\n")
study_location = input("Де Ви навчаєтесь?\n")
group_number = int(input("Номер Вашої групи?\n"))
list_number = int(input("Який Ваш порядковий номер у списку групи?\n"))
question = input("Сьогодні сонячно?\n")
print("\nВведені дані:\n")
print("ПІБ: ", full_name, "\n")
print("Вік: ", age, "\n")
print("Місце проживання: ", location, "\n")
print("Місце навчання: ", study_location, "\n")
print("Номер групи: ", group_number, "\n")
print("Номер у журналі: ", list_number, "\n")
print("Сьогодні сонячно?: ", question, "\n")
